const CARDS = [
    { value: 2, name: '2', type: 'Hearts' },
    { value: 2, name: '2', type: 'Diamonds' },
    { value: 2, name: '2', type: 'Clubs' },
    { value: 2, name: '2', type: 'Spades' },
    { value: 3, name: '3', type: 'Hearts' },
    { value: 3, name: '3', type: 'Diamonds' },
    { value: 3, name: '3', type: 'Clubs' },
    { value: 3, name: '3', type: 'Spades' },
    { value: 4, name: '4', type: 'Hearts' },
    { value: 4, name: '4', type: 'Diamonds' },
    { value: 4, name: '4', type: 'Clubs' },
    { value: 4, name: '4', type: 'Spades' },
    { value: 5, name: '5', type: 'Hearts' },
    { value: 5, name: '5', type: 'Diamonds' },
    { value: 5, name: '5', type: 'Clubs' },
    { value: 5, name: '5', type: 'Spades' },
    { value: 6, name: '6', type: 'Hearts' },
    { value: 6, name: '6', type: 'Diamonds' },
    { value: 6, name: '6', type: 'Clubs' },
    { value: 6, name: '6', type: 'Spades' },
    { value: 7, name: '7', type: 'Hearts' },
    { value: 7, name: '7', type: 'Diamonds' },
    { value: 7, name: '7', type: 'Clubs' },
    { value: 7, name: '7', type: 'Spades' },
    { value: 8, name: '8', type: 'Hearts' },
    { value: 8, name: '8', type: 'Diamonds' },
    { value: 8, name: '8', type: 'Clubs' },
    { value: 8, name: '8', type: 'Spades' },
    { value: 9, name: '9', type: 'Hearts' },
    { value: 9, name: '9', type: 'Diamonds' },
    { value: 9, name: '9', type: 'Clubs' },
    { value: 9, name: '9', type: 'Spades' },
    { value: 10, name: '10', type: 'Hearts' },
    { value: 10, name: '10', type: 'Diamonds' },
    { value: 10, name: '10', type: 'Clubs' },
    { value: 10, name: '10', type: 'Spades' },
    { value: 10, name: 'Jack', type: 'Hearts' },
    { value: 10, name: 'Jack', type: 'Diamonds' },
    { value: 10, name: 'Jack', type: 'Clubs' },
    { value: 10, name: 'Jack', type: 'Spades' },
    { value: 10, name: 'Queen', type: 'Hearts' },
    { value: 10, name: 'Queen', type: 'Diamonds' },
    { value: 10, name: 'Queen', type: 'Clubs' },
    { value: 10, name: 'Queen', type: 'Spades' },
    { value: 10, name: 'King', type: 'Hearts' },
    { value: 10, name: 'King', type: 'Diamonds' },
    { value: 10, name: 'King', type: 'Clubs' },
    { value: 10, name: 'King', type: 'Spades' },
    { value: 11, name: 'Ace', type: 'Hearts' },
    { value: 11, name: 'Ace', type: 'Diamonds' },
    { value: 11, name: 'Ace', type: 'Clubs' },
    { value: 11, name: 'Ace', type: 'Spades' }
  ];

  module.exports = {
    CARDS
  }